// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDietitianMobileApp.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyDietitianMobileApp.Infrastructure.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316013958_Sprint1_MealTypeAndAlternativeCompletion")]
    partial class Sprint1_MealTypeAndAlternativeCompletion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.AccessKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DietitianId", "ClientId");

                    b.ToTable("AccessKeys");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveDietitianId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PremiumActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProgramEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProgramStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDietitianId");

                    b.HasIndex("DietitianId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetaJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "AtUtc")
                        .IsDescending(false, true);

                    b.HasIndex("DietitianId", "AtUtc")
                        .IsDescending(false, true)
                        .HasFilter("\"DietitianId\" IS NOT NULL");

                    b.ToTable("ClientActivities");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientDailyTracking", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Steps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WaterGlasses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("ClientId", "Date");

                    b.HasIndex("ClientId", "Date")
                        .IsDescending(false, true);

                    b.ToTable("ClientDailyTrackings");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientIngredientProhibition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ClientIngredientProhibitions");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientMealPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientMealPlanId");

                    b.HasIndex("RecipeId");

                    b.ToTable("ClientMeals");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientMealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DietitianId");

                    b.ToTable("ClientMealPlans");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientMeasurementEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ChestCm")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("HipCm")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WaistCm")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "AtUtc")
                        .IsDescending(false, true);

                    b.ToTable("ClientMeasurementEntries");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientPantryItem", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ClientId", "UpdatedAtUtc");

                    b.ToTable("ClientPantryItems");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientProhibitedIngredient", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientId", "IngredientId");

                    b.HasIndex("ClientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ClientId", "CreatedAtUtc");

                    b.ToTable("ClientProhibitedIngredients");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientWeightEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "AtUtc")
                        .IsDescending(false, true);

                    b.ToTable("ClientWeightEntries");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ComplianceScoreConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DietPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<int>("MandatoryAlternative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(7);

                    b.Property<int>("MandatoryDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("MandatorySkipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("OptionalDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int>("OptionalSkipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DietPlanId");

                    b.HasIndex("DietitianId");

                    b.HasIndex("DietitianId", "DietPlanId")
                        .IsUnique();

                    b.ToTable("ComplianceScoreConfigs");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DailyComplianceSnapshot", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("CompletedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("PlannedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Score0_100")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("SkippedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientId", "Date");

                    b.ToTable("DailyComplianceSnapshots");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DietitianId");

                    b.HasIndex("ClientId", "Status");

                    b.ToTable("DietPlans");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlanDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DailyTargetCalories")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DietPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DietPlanId");

                    b.HasIndex("DietPlanId", "Date")
                        .IsUnique();

                    b.ToTable("DietPlanDays");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlanMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("DietPlanDayId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PlannedRecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DietPlanDayId");

                    b.HasIndex("DietPlanDayId", "Type");

                    b.ToTable("DietPlanMeals");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Dietitian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Dietitians");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietitianBrandingConfig", b =>
                {
                    b.Property<Guid>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccentColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#FF8C61");

                    b.Property<string>("ClinicName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PrimaryColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#4A7C59");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DietitianId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("DietitianBrandingConfigs");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietitianClientLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublicUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UnlinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DietitianId", "ClientId");

                    b.ToTable("DietitianClientLinks");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietitianNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DietitianId", "ClientId", "CreatedAtUtc")
                        .IsDescending(false, false, true);

                    b.ToTable("DietitianNotes");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietitianSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccentColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#8FBC8F");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DietitianDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PrimaryColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#4A7C59");

                    b.Property<string>("ThemePresetKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("DietitianId")
                        .IsUnique();

                    b.ToTable("DietitianSettings");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProhibited")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalName");

                    b.HasIndex("IsActive");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.IngredientCompatibilityRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateIngredientId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompatibilityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RequiredIngredientId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ScorePenalty")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateIngredientId");

                    b.HasIndex("IsActive");

                    b.HasIndex("RequiredIngredientId");

                    b.HasIndex("RequiredIngredientId", "CandidateIngredientId")
                        .IsUnique();

                    b.ToTable("IngredientCompatibilityRules");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.IngredientFamily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("IngredientFamilies");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.IngredientFamilyMember", b =>
                {
                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("FamilyId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientFamilyMembers");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.IngredientNormalizationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateSummaryJson")
                        .HasColumnType("jsonb");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatchedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MatchedCanonicalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("MatchedIngredientId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedInput")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RawInput")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("MatchedBy");

                    b.HasIndex("MatchedIngredientId");

                    b.HasIndex("Status");

                    b.ToTable("IngredientNormalizationLogs");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.IngredientPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DietitianId");

                    b.HasIndex("IsSystem");

                    b.HasIndex("IsSystem", "SortOrder");

                    b.ToTable("IngredientPacks");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.IngredientPackItem", b =>
                {
                    b.Property<Guid>("PackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.HasKey("PackId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientPackItems");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlternativeRecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DietPlanMealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DietitianId");

                    b.HasIndex("ClientId", "AtUtc")
                        .IsDescending(false, true);

                    b.HasIndex("ClientId", "DietPlanMealId")
                        .IsUnique();

                    b.ToTable("MealCompletions");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealCompliance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlternativeRecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DietPlanMealId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DietPlanMealId");

                    b.ToTable("MealCompliances");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("DietPlanMealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DietPlanMealId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MealId");

                    b.ToTable("MealItems");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealItemCompliance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlternativeIngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ClientTimezoneOffsetMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("DietDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DietPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MealItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DietDayId");

                    b.HasIndex("DietPlanId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MarkedAt");

                    b.HasIndex("MealId");

                    b.HasIndex("MealItemId");

                    b.HasIndex("ClientId", "DietPlanId");

                    b.HasIndex("ClientId", "MarkedAt");

                    b.HasIndex("ClientId", "MealItemId", "DietDayId")
                        .IsUnique();

                    b.ToTable("MealItemCompliance");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_MealPlans_Status");

                    b.HasIndex("ClientId", "Date")
                        .HasDatabaseName("IX_MealPlans_ClientId_Date");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.PlanMealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CarbsGrams")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<Guid?>("CompletionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("FatGrams")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<int>("MealType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6);

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ProteinGrams")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompletionId");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("IX_PlanMealItems_PlanId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("Time")
                        .HasDatabaseName("IX_PlanMealItems_Time");

                    b.ToTable("PlanMealItems");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.PremiumAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetaJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AtUtc");

                    b.HasIndex("ClientId");

                    b.HasIndex("DietitianId");

                    b.ToTable("PremiumAuditLogs");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DietitianId");

                    b.HasIndex("IsPublic");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.RecipeIngredientSubstitute", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequiredIngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubstituteIngredientId")
                        .HasColumnType("uuid");

                    b.HasKey("RecipeId", "RequiredIngredientId", "SubstituteIngredientId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("RequiredIngredientId");

                    b.HasIndex("SubstituteIngredientId");

                    b.HasIndex("RecipeId", "RequiredIngredientId");

                    b.ToTable("RecipeIngredientSubstitutes");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.RecipeProhibition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeProhibitions");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.RecipeRecommendationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalMetaJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DietitianId")
                        .HasColumnType("uuid");

                    b.Property<string>("Flow")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("MatchPercentage")
                        .HasColumnType("numeric");

                    b.Property<int>("MissingMandatoryCount")
                        .HasColumnType("integer");

                    b.Property<string>("MissingMandatoryIdsJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("OriginalCookable")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PlannedRecipeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ProhibitedRejected")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SelectedRecipeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("UsedSubstitutes")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DietitianId");

                    b.HasIndex("Flow");

                    b.HasIndex("PlannedRecipeId");

                    b.HasIndex("SelectedRecipeId");

                    b.ToTable("RecipeRecommendationLogs");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.RecipeSubstitute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequiredIngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubstituteIngredientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("RequiredIngredientId");

                    b.HasIndex("SubstituteIngredientId");

                    b.ToTable("RecipeSubstitutes");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.UserMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Bmi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Bmr")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HeightCm")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "CreatedAt");

                    b.ToTable("UserMeasurements");
                });

            modelBuilder.Entity("RecipeMandatoryIngredients", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeMandatoryIngredients");
                });

            modelBuilder.Entity("RecipeOptionalIngredients", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeOptionalIngredients");
                });

            modelBuilder.Entity("RecipeProhibitedIngredients", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeProhibitedIngredients");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.AccessKey", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", null)
                        .WithMany("AccessKeys")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Client", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Dietitian", null)
                        .WithMany("Clients")
                        .HasForeignKey("DietitianId");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientActivity", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Dietitian", "Dietitian")
                        .WithMany()
                        .HasForeignKey("DietitianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Dietitian");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientDailyTracking", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientIngredientProhibition", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientMeal", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.ClientMealPlan", "ClientMealPlan")
                        .WithMany("Meals")
                        .HasForeignKey("ClientMealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientMealPlan");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientMealPlan", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Dietitian", "Dietitian")
                        .WithMany()
                        .HasForeignKey("DietitianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Dietitian");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientMeasurementEntry", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientPantryItem", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientProhibitedIngredient", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientWeightEntry", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DailyComplianceSnapshot", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlanDay", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlan", "DietPlan")
                        .WithMany("Days")
                        .HasForeignKey("DietPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietPlan");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlanMeal", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlanDay", "DietPlanDay")
                        .WithMany("Meals")
                        .HasForeignKey("DietPlanDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietPlanDay");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietitianBrandingConfig", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Dietitian", "Dietitian")
                        .WithOne()
                        .HasForeignKey("MyDietitianMobileApp.Domain.Entities.DietitianBrandingConfig", "DietitianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dietitian");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietitianClientLink", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietitianNote", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Dietitian", "Dietitian")
                        .WithMany()
                        .HasForeignKey("DietitianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Dietitian");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietitianSettings", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Dietitian", "Dietitian")
                        .WithOne()
                        .HasForeignKey("MyDietitianMobileApp.Domain.Entities.DietitianSettings", "DietitianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dietitian");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.IngredientCompatibilityRule", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", "CandidateIngredient")
                        .WithMany()
                        .HasForeignKey("CandidateIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", "RequiredIngredient")
                        .WithMany()
                        .HasForeignKey("RequiredIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateIngredient");

                    b.Navigation("RequiredIngredient");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.IngredientFamilyMember", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.IngredientFamily", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.IngredientPackItem", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.IngredientPack", "Pack")
                        .WithMany("Items")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealCompletion", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Dietitian", "Dietitian")
                        .WithMany()
                        .HasForeignKey("DietitianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Dietitian");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealCompliance", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlanMeal", "DietPlanMeal")
                        .WithMany()
                        .HasForeignKey("DietPlanMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("DietPlanMeal");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealItem", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlanMeal", null)
                        .WithMany("Items")
                        .HasForeignKey("DietPlanMealId");

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlanMeal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealItemCompliance", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlanDay", null)
                        .WithMany()
                        .HasForeignKey("DietDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlan", null)
                        .WithMany()
                        .HasForeignKey("DietPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.DietPlanMeal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.MealItem", null)
                        .WithMany()
                        .HasForeignKey("MealItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealPlan", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Dietitian", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.PlanMealItem", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.MealCompletion", "Completion")
                        .WithMany()
                        .HasForeignKey("CompletionId");

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.MealPlan", "Plan")
                        .WithMany("Items")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Completion");

                    b.Navigation("Plan");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Dietitian", null)
                        .WithMany("Recipes")
                        .HasForeignKey("DietitianId");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.RecipeIngredientSubstitute", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", "RequiredIngredient")
                        .WithMany()
                        .HasForeignKey("RequiredIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", "SubstituteIngredient")
                        .WithMany()
                        .HasForeignKey("SubstituteIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("RequiredIngredient");

                    b.Navigation("SubstituteIngredient");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.RecipeProhibition", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.RecipeSubstitute", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", "RequiredIngredient")
                        .WithMany()
                        .HasForeignKey("RequiredIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", "SubstituteIngredient")
                        .WithMany()
                        .HasForeignKey("SubstituteIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("RequiredIngredient");

                    b.Navigation("SubstituteIngredient");
                });

            modelBuilder.Entity("RecipeMandatoryIngredients", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeOptionalIngredients", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeProhibitedIngredients", b =>
                {
                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyDietitianMobileApp.Domain.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Client", b =>
                {
                    b.Navigation("AccessKeys");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.ClientMealPlan", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlan", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlanDay", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.DietPlanMeal", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.Dietitian", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.IngredientFamily", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.IngredientPack", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MyDietitianMobileApp.Domain.Entities.MealPlan", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
