import Link from "next/link";
import { Check, HelpCircle } from "lucide-react";
import { CTA, PageShell, Tag } from "@/components/marketing/MarketingSite";

const plans = [["Başlangıç","3 ay","Dijital klinik modelini kontrollü bir danışan grubuyla başlatın."],["Büyüme","6 ay","Düzenli danışan operasyonunu güçlü bir sisteme taşıyın."],["Klinik","12 ay","Dytopia’yı kliniğinizin ana dijital altyapısı olarak kullanın."],["Uzun dönem","24 ay","Sürdürülebilir dijital klinik operasyonu için en uzun lisans dönemi."]];
export default function PricingPage() {
 return <PageShell><section className="px-5 py-20 text-center lg:px-8 lg:py-28"><Tag>Premium lisans</Tag><h1 className="mx-auto mt-7 max-w-5xl text-5xl font-black leading-[.98] tracking-[-.06em] sm:text-7xl">Her pakette eksiksiz Dytopia deneyimi.</h1><p className="mx-auto mt-7 max-w-3xl text-lg font-medium leading-8 text-[#557269]">Modül satışı ve karmaşık ücretsiz planlar yok. Web paneli ve danışan mobil deneyimi tüm lisanslarda birlikte çalışır.</p></section>
 <section className="px-5 pb-24 lg:px-8"><div className="mx-auto grid max-w-[1320px] gap-4 md:grid-cols-2 xl:grid-cols-4">{plans.map((p,i)=><article key={p[0]} className={`rounded-[1.8rem] border p-7 shadow-[0_20px_55px_rgba(20,80,55,.08)] ${i===2?"border-emerald-400 bg-[#073c2c] text-white":"border-[#0b4c36]/10 bg-white"}`}><p className={`text-xs font-black uppercase tracking-[.18em] ${i===2?"text-emerald-300":"text-emerald-700"}`}>{p[0]}</p><h2 className="mt-5 text-5xl font-black">{p[1]}</h2><p className={`mt-5 min-h-24 text-sm font-medium leading-7 ${i===2?"text-white/60":"text-[#5a756c]"}`}>{p[2]}</p><ul className="mt-7 grid gap-3 text-sm font-bold">{["Tam web panel","Danışan mobil uygulaması","Access key sistemi","Tüm ürün güncellemeleri"].map(x=><li key={x} className="flex gap-2"><Check size={16} className={i===2?"text-emerald-300":"text-emerald-600"}/>{x}</li>)}</ul><Link href="/iletisim" className={`mt-8 block rounded-full py-3.5 text-center text-sm font-black ${i===2?"bg-white text-[#073c2c]":"bg-emerald-50 text-emerald-800"}`}>Teklif alın</Link></article>)}</div></section>
 <section className="bg-[#e8f6ed] px-5 py-20 lg:px-8"><div className="mx-auto max-w-4xl"><Tag>Sık sorulanlar</Tag><div className="mt-8 grid gap-3">{[["Ücretsiz plan var mı?","Hayır. Dytopia baştan sona premium klinik deneyimi olarak sunulur."],["Fiyatlar neden sayfada yok?","Lisans kapsamı ve klinik ihtiyacı görüşmede netleştirilerek doğru teklif hazırlanır."],["Mobil uygulama pakete dahil mi?","Evet. Web panel ve danışan mobil uygulaması birlikte sunulur."],["Kurulum desteği veriliyor mu?","Evet. Klinik yapısı, erişim ve başlangıç süreci birlikte planlanır."]].map(([q,a])=><div key={q} className="rounded-2xl border border-[#0b4c36]/10 bg-white p-5"><h3 className="flex items-center gap-2 font-black"><HelpCircle size={17} className="text-emerald-600"/>{q}</h3><p className="mt-2 text-sm font-medium leading-6 text-[#5a756c]">{a}</p></div>)}</div></div></section><CTA/></PageShell>
}
